export const PLANS = [
  {
    slug: "mensal",
    name: "Mensal",
    months: 1,
    highlight: "Para conhecer o painel sem compromisso longo",
    contract: "Contrato de 30 dias",
    creativeSupport: ["Troca de arte no período"],
    exclusive: false,
    featured: false,
  },
  {
    slug: "trimestral",
    name: "Trimestral",
    months: 3,
    highlight: "Para testar o painel com constância real",
    contract: "Contrato de 90 dias",
    creativeSupport: ["1 troca de arte no período"],
    exclusive: true,
    featured: false,
  },
  {
    slug: "semestral",
    name: "Semestral",
    months: 6,
    highlight: "Equilíbrio entre compromisso e flexibilidade",
    contract: "Contrato de 6 meses",
    creativeSupport: ["Troca de arte a cada 60 dias", "Revisão criativa sazonal"],
    exclusive: true,
    featured: false,
  },
  {
    slug: "anual",
    name: "Anual",
    months: 12,
    badge: "Mais vendido",
    highlight: "Melhor valor mensal e presença contínua",
    contract: "Contrato de 12 meses",
    creativeSupport: ["Troca de arte mensal", "Planejamento de datas e campanhas do ano"],
    exclusive: true,
    featured: true,
  },
] as const;

export const PLAN_OPTIONS = PLANS.map((plan) => plan.name);
